// Copyright (c) 2020 Chris Richardson
// FEniCS Project
// SPDX-License-Identifier:    MIT

#pragma once

#define BASIX_VERSION @PROJECT_VERSION@
#define BASIX_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define BASIX_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define BASIX_VERSION_PATCH @PROJECT_VERSION_PATCH@
