from ._basixcpp import DPCVariant as _DV, LagrangeVariant as _LV

def string_to_lagrange_variant(variant: str) -> _LV: ...
def lagrange_variant_to_string(variant: _LV) -> str: ...
def string_to_dpc_variant(variant: str) -> _DV: ...
def dpc_variant_to_string(variant: _DV) -> str: ...
