name: FFCx integration

# Install Basix and FFCx and run the FFCx unit tests.

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "main"
  merge_group:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run FFCx tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Load environment variables
        run: cat .github/workflows/fenicsx-refs.env >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: sudo apt-get install -y libopenblas-dev liblapack-dev graphviz libgraphviz-dev ninja-build
      - name: Install UFL
        run: pip install git+https://github.com/${{ env.ufl_repository }}.git@${{ env.ufl_ref }}
      - name: Install Basix
        run: pip -v install .[ci]
      - name: Get FFCx source
        uses: actions/checkout@v6
        with:
          path: ./ffcx
          repository: ${{ env.ffcx_repository }}
          ref: ${{ env.ffcx_ref }}
      - name: Install FFCx
        run: pip install ./ffcx[ci]
      - name: Run FFCx tests
        working-directory: ffcx/test
        run: >
          pytest .
          -n auto
          --ignore=ffcx/test/test_lnodes.py
          --ignore=ffcx/test/test_custom_data.py
