name: Red Hat clone

# This workflow will test Basix on Red Hat

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test (Red Hat)
    runs-on: ubuntu-24.04
    container: rockylinux/rockylinux:10
    env:
      CC: gcc
      CXX: g++
    steps:
      - name: Install dependencies
        run: |
          dnf -y update
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf install -y openblas-devel cmake gcc gcc-c++ git lapack-devel python3 python3-devel python3-pip
      - name: Upgrade pip
        run: python3 -m pip install pip --upgrade
      - uses: actions/checkout@v7
      - name: Install Basix
        run: python3 -m pip install -Ccmake.build-type="Developer" .[test]
      - name: Run units tests
        run: python3 -m pytest --durations 20 test/
      - name: Run Python demos
        run: python3 -m pytest demo/python/test.py
      - name: Run C++ demos
        run: python3 -m pytest demo/cpp/test.py
